### ISSUE TITLE
Add power and key mini-relays

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/TouCans#6]
Move the relays inside the can! Use a Darlington array to link the Pico-W to the relays.

Pico-W pinout with Darlington inputs
![image](https://github.com/user-attachments/assets/6e059932-b061-4413-b9f3-a3041c08af42)

Latching relay usage video (HFD2)
https://www.youtube.com/watch?v=QKK3v73P_44

Relay for keyer pinout from below:
![image](https://github.com/user-attachments/assets/9501bdd7-1537-47a9-911e-9b64baafe5ff)

[data sheet for relay](https://omronfs.omron.com/en_US/ecb/products/pdf/en-g5v_1.pdf)

[data sheet for Darlington array](https://www.ti.com/lit/ds/symlink/uln2003a.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1726602878998&ref_url=https%253A%252F%252Fwww.ti.com%252Fgeneral%252Fdocs%252Fsuppproductinfo.tsp%253FdistId%253D10%2526gotoUrl%253Dhttps%253A%252F%252Fwww.ti.com%252Flit%252Fgpn%252Fuln2003a)

Darlington Array pinout
![image](https://github.com/user-attachments/assets/e38c6751-92e0-4263-9b0e-8d26a19e9509)

Typical usage of Darlington Array
![image](https://github.com/user-attachments/assets/1b381edd-8b36-4a9a-8001-40d98aa58cfb)

Proposed device layout (using superglue)
![image](https://github.com/user-attachments/assets/38925eca-9fd1-4ab4-8db1-a3c6d5bc96d3)

**Comment by hcarter333** [comment]
Superglue relay to board

**Comment by arhonah** [comment]
this is the drawing of how we're going to set this up
![image](https://github.com/user-attachments/assets/8e812475-ca26-48de-8630-27433d7c3312)

**Comment by hcarter333** [comment]
[Completed](https://copaseticflow.blogspot.com/2024/11/the-project-toucans-power-system.html).
